spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: 'true'
    hibernate:
      ddl-auto: create
    show-sql: 'true'
    database-platform: org.hibernate.dialect.H2Dialect

  datasource:
    driverClassName: org.h2.Driver
    password: '1'
    username: sa
    url: jdbc:h2:tcp://localhost/~/car

  h2:
    console:
      path: /h2-console
      enabled: 'true'

jwt:
  token:
    secret-key: 'adsadasdasdasdasadasdasdasdasdasdadassdasaaa'
    expire-date:
      access-token: 1234